spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090

  datasource:
    username: adminuser
    password: adminpassword
    url: jdbc:postgresql://localhost:5432/providers_db

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  h2:
    console:
      enabled: true

logging:
  level:
    root: info
    org.springframework.web: info
    org.springframework.security: debug
    org.springframework.security.oauth2: debug
    org.springframework.data.redis: debug
    web: debug

server:
  port: 4747